### ISSUE TITLE
Is there a way to have a smaller "runtime only" OpenDDS docker container?

### ISSUE THREAD

**Issue by Cingulara** [objectcomputing/OpenDDS#1383]
Is there a way to have a 'runtime only' option for a container where I can compile my app within the OpenDDS container like the Dev Guide says now, but my exectuable would be in a 'runtime only' type of container? I liken this to the C# SDK container from Microsoft being huge but the runtime version you copy your compiled code into being a lot smaller of a container in size. 

The docker-compose w/ the Info server for discovery runs 3 containers. That is 3 2GB containers running where 1 is the Info server, 1 the subscriber and 1 the producer. Is there a way to shrink the containers for runtime files only that are needed? No test scripts. No extras. Just the minimum files needed so the "publisher" executable can run correctly in that container? 

I saw the https://github.com/jrw972/KubernetesMessenger info and the https://opendds.org/quickstart/GettingStartedDocker.html information and both worked well. However, the image itself is 2GB when I do a `docker images | grep opendds` and see the actual size.  I am trying to not run the "SDK" version and run the "runtime only" version of this if that makes sense. 

Is everything in /opt/OpenDDS actually required to run the application? like the ./tests/ directory? Or the PROBLEM-REPORT-FORM file? I am asking so I can shrink the image size down for memory usage, transport, etc.

**Comment by Cingulara** [comment]
I am coming from a NATS.io type of messaging so this is more robust from the server end and all you can do with it. I can compile golang clients for subscribers to a single executable and copy to a Dockerfile "FROM scratch" to make a 11MB size image as an example. That is a very simplistic example of course. 

If I look at the .NET Core 3.0 SDK image it is 1.74 GB.
If I look at the .NET Core runtime image it is 189 MB.
And look at the .NET Core ASPNET is 207 MB.

I can build in the SDK, the copy contents into one of the runtimes to make my image smaller. That is what I am getting at. Not sure if there is a way to do that here? if it is even possible with the architecture? if it is on the roadmap?

**Comment by mitza-oci** [comment]
You can build OpenDDS as static libraries (I believe this is the approach that golang uses).  Or even with shared libraries, you can copy just what you need into your container.

**Comment by Cingulara** [comment]
Ok.  Do you have any developer documentation you can show me where I should
put stuff into the container? And yes that’s exactly how Golang does it. I
need to start working on that tomorrow and I wanted to make sure I’m doing
it correctly. Or are there any pointers you can send me to on your website
to make sure I’m building that correctly?

Thank you for the quick response.
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by Cingulara** [comment]
So instead of the below, I would have compiled binaries that would do the same thing that these three below do:

```
version: '2'
services:
  inforepo:
    image: objectcomputing/opendds
    command: DCPSInfoRepo -ORBListenEndpoints iiop://:3897
    volumes:
      - $PWD:/opt/workspace
  subscriber:
    image: objectcomputing/opendds
    command: ["./wait-for-it.sh", "inforepo:3897", "--", "subscriber", "-DCPSInfoRepo",  "inforepo:3897" ]
    volumes:
      - $PWD:/opt/workspace
  publisher:
    image: objectcomputing/opendds
    command: ["./wait-for-it.sh", "inforepo:3897", "--", "publisher", "-DCPSInfoRepo",  "inforepo:3897" ]
    volumes:
      - $PWD:/opt/workspace
```
