### ISSUE TITLE
where is the ELF

### ISSUE THREAD

**Issue by fengxiaohu** [objectcomputing/OpenDDS#3539]

**Comment by fengxiaohu** [comment]
I see the shapes demo in quickstart: https://opendds.org/quickstart/GettingStartedShapesDemo.html
if I want to rebuild the projct and modify the GUI.where is the ELF file(ishapes)

for example: 
`./ishapes`


![image](https://user-images.githubusercontent.com/23492381/172055702-ac2120ec-4562-4994-afa5-f27c88264596.png)

**Comment by iguessthislldo** [comment]
If you built with [Qt enabled](https://github.com/objectcomputing/OpenDDS/blob/master/docs/qt.md), the `ishapes` binary should be in its project directory: `examples/DCPS/ishapes`.

**Comment by fengxiaohu** [comment]
> If you built with [Qt enabled](https://github.com/objectcomputing/OpenDDS/blob/master/docs/qt.md), the `ishapes` binary should be in its project directory: `examples/DCPS/ishapes`.

thanks for solving my question.
Here are my steps:

-  clone the project to Ubuntu 
- run `./configure` download and configure automatically 
- run `make` to compile

end(So what should I do next to generate *ishapes*,would you mind  solving my problem?)

**Comment by mitza-oci** [comment]
Build with Qt enabled.  Here's some more info in case it's helpful:

https://github.com/objectcomputing/OpenDDS/blob/master/examples/DCPS/ishapes/README.md

https://github.com/objectcomputing/OpenDDS/actions/runs/2235010104/workflow

**Comment by fengxiaohu** [comment]
> https://github.com/objectcomputing/OpenDDS/actions/runs/2235010104/workflow
thank u, it is really helpful

**Comment by fengxiaohu** [comment]
sorry to reopen it.
I check the workflow file
```
Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: update apt
      run: sudo apt-get update
    - name: install qt
      run: sudo apt-get -y install qtbase5-dev
    - name: checkout OpenDDS
      uses: actions/checkout@v3
      with:
        path: OpenDDS
        submodules: true
    - name: checkout ACE_TAO
      uses: actions/checkout@v3
      with:
        repository: DOCGroup/ACE_TAO
        ref: Latest_Micro
        path: OpenDDS/ACE_TAO
    - name: get ACE_TAO commit
      shell: bash
      run: |
        cd OpenDDS/ACE_TAO
        export ACE_COMMIT=$(git rev-parse HEAD)
        echo "ACE_COMMIT=$ACE_COMMIT" >> $GITHUB_ENV
    - name: get compiler version
      shell: bash
      run: |
        export COMPILER_VERSION=$(c++ --version 2>&1 | head -n 1)
        echo "COMPILER_VERSION=$COMPILER_VERSION" >> $GITHUB_ENV
    - name: checkout MPC
      uses: actions/checkout@v3
      with:
        repository: DOCGroup/MPC
        path: OpenDDS/ACE_TAO/ACE/MPC
    - name: configure OpenDDS
      run: |
        cd OpenDDS
        ./configure --optimize --no-debug --static --tests --qt
        tools/scripts/show_build_config.pl
    - uses: ammaraskar/gcc-problem-matcher@0.1
    - name: build
      shell: bash
      run: |
        cd OpenDDS
        make -j4 ishapes
    - name: upload ishapes artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.job }}_artifact
        path: OpenDDS/examples/DCPS/ishapes/ishapes
```
I find that I forget to configure qt So excute
`cd OpenDS-3.20`

`./configure --qt`

`make ishapes`
 but I failed in `make ishapes` it remides me like that:
![image](https://user-images.githubusercontent.com/23492381/172117758-64381a1c-cd8b-4ff2-8cf3-49102d4017a9.png)

Would you like to give me some suggestions
